<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net6.0</TargetFramework>
		<ImplicitUsings>disable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<PlatformTarget>AnyCPU</PlatformTarget>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <!-- 游戏路径 -->
    <TaiwuPath>D:\SteamLibrary\steamapps\common\The Scroll Of Taiwu</TaiwuPath>
	</PropertyGroup>

	<ItemGroup>
	  <None Remove="Config.lua" />
	</ItemGroup>

	<ItemGroup>
	  <Content Include="Config.lua" />
	</ItemGroup>

  <ItemGroup>
    <Reference Include="0Harmony">
      <HintPath>$(TaiwuPath)\The Scroll of Taiwu_Data\Managed\0Harmony.dll</HintPath>
    </Reference>
    <Reference Include="GameData">
      <HintPath>$(TaiwuPath)\Backend\GameData.dll</HintPath>
    </Reference>
    <Reference Include="Redzen">
      <HintPath>$(TaiwuPath)\Backend\Redzen.dll</HintPath>
    </Reference>
    <Reference Include="TaiwuModdingLib">
      <HintPath>$(TaiwuPath)\The Scroll of Taiwu_Data\Managed\TaiwuModdingLib.dll</HintPath>
    </Reference>
    <Reference Include="Taiwu_EventPackage_CharacterInteraction_Interact">
      <HintPath>$(TaiwuPath)\Event\EventLib\Taiwu_EventPackage_CharacterInteraction_Interact.dll</HintPath>
    </Reference>
    <Reference Include="Taiwu_EventPackage_CharacterInteraction_Main">
      <HintPath>$(TaiwuPath)\Event\EventLib\Taiwu_EventPackage_CharacterInteraction_Main.dll</HintPath>
    </Reference>
    <Reference Include="Taiwu_EventPackage_CharacterInteraction_Relate">
      <HintPath>$(TaiwuPath)\Event\EventLib\Taiwu_EventPackage_CharacterInteraction_Relate.dll</HintPath>
    </Reference>
  </ItemGroup>



</Project>
