<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <!-- 游戏路径 -->
    <TaiwuPath>D:\SteamLibrary\steamapps\common\The Scroll Of Taiwu</TaiwuPath>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="0Harmony">
      <HintPath>$(TaiwuPath)\The Scroll of Taiwu_Data\Managed\0Harmony.dll</HintPath>
    </Reference>
    <Reference Include="GameData">
      <HintPath>$(TaiwuPath)\Backend\GameData.dll</HintPath>
    </Reference>
    <Reference Include="TaiwuModdingLib">
      <HintPath>$(TaiwuPath)\The Scroll of Taiwu_Data\Managed\TaiwuModdingLib.dll</HintPath>
    </Reference>
    <Reference Include="Taiwu_EventPackage_CharacterInteraction_Interact">
      <HintPath>$(TaiwuPath)\Event\EventLib\Taiwu_EventPackage_CharacterInteraction_Interact.dll</HintPath>
    </Reference>
    <Reference Include="Taiwu_EventPackage_CharacterInteraction_Main">
      <HintPath>$(TaiwuPath)\Event\EventLib\Taiwu_EventPackage_CharacterInteraction_Main.dll</HintPath>
    </Reference>
    <Reference Include="Taiwu_EventPackage_CharacterInteraction_RandomEnemy">
      <HintPath>$(TaiwuPath)\Event\EventLib\Taiwu_EventPackage_CharacterInteraction_RandomEnemy.dll</HintPath>
    </Reference>
    <Reference Include="Taiwu_EventPackage_CharacterInteraction_Relate">
      <HintPath>$(TaiwuPath)\Event\EventLib\Taiwu_EventPackage_CharacterInteraction_Relate.dll</HintPath>
    </Reference>
    <Reference Include="Taiwu_EventPackage_MainStory_DeepValley">
      <HintPath>$(TaiwuPath)\Event\EventLib\Taiwu_EventPackage_MainStory_DeepValley.dll</HintPath>
    </Reference>
    <Reference Include="Taiwu_EventPackage_MarryAdventure">
      <HintPath>$(TaiwuPath)\Event\EventLib\Taiwu_EventPackage_MarryAdventure.dll</HintPath>
    </Reference>
    <Reference Include="Taiwu_EventPackage_MarryChengDu">
      <HintPath>$(TaiwuPath)\Event\EventLib\Taiwu_EventPackage_MarryChengDu.dll</HintPath>
    </Reference>
    <Reference Include="Taiwu_EventPackage_MarryDaLi">
      <HintPath>$(TaiwuPath)\Event\EventLib\Taiwu_EventPackage_MarryDaLi.dll</HintPath>
    </Reference>
    <Reference Include="Taiwu_EventPackage_MarryFuZhou">
      <HintPath>$(TaiwuPath)\Event\EventLib\Taiwu_EventPackage_MarryFuZhou.dll</HintPath>
    </Reference>
    <Reference Include="Taiwu_EventPackage_MarryGuangZhou">
      <HintPath>$(TaiwuPath)\Event\EventLib\Taiwu_EventPackage_MarryGuangZhou.dll</HintPath>
    </Reference>
    <Reference Include="Taiwu_EventPackage_MarryGuiZhou">
      <HintPath>$(TaiwuPath)\Event\EventLib\Taiwu_EventPackage_MarryGuiZhou.dll</HintPath>
    </Reference>
    <Reference Include="Taiwu_EventPackage_MarryHangZhou">
      <HintPath>$(TaiwuPath)\Event\EventLib\Taiwu_EventPackage_MarryHangZhou.dll</HintPath>
    </Reference>
    <Reference Include="Taiwu_EventPackage_MarryJiangLing">
      <HintPath>$(TaiwuPath)\Event\EventLib\Taiwu_EventPackage_MarryJiangLing.dll</HintPath>
    </Reference>
    <Reference Include="Taiwu_EventPackage_MarryJingCheng">
      <HintPath>$(TaiwuPath)\Event\EventLib\Taiwu_EventPackage_MarryJingCheng.dll</HintPath>
    </Reference>
    <Reference Include="Taiwu_EventPackage_MarryLiaoYang">
      <HintPath>$(TaiwuPath)\Event\EventLib\Taiwu_EventPackage_MarryLiaoYang.dll</HintPath>
    </Reference>
    <Reference Include="Taiwu_EventPackage_MarryQingZhou">
      <HintPath>$(TaiwuPath)\Event\EventLib\Taiwu_EventPackage_MarryQingZhou.dll</HintPath>
    </Reference>
    <Reference Include="Taiwu_EventPackage_MarryQinZhou">
      <HintPath>$(TaiwuPath)\Event\EventLib\Taiwu_EventPackage_MarryQinZhou.dll</HintPath>
    </Reference>
    <Reference Include="Taiwu_EventPackage_MarryShouChun">
      <HintPath>$(TaiwuPath)\Event\EventLib\Taiwu_EventPackage_MarryShouChun.dll</HintPath>
    </Reference>
    <Reference Include="Taiwu_EventPackage_MarryTaiYuan">
      <HintPath>$(TaiwuPath)\Event\EventLib\Taiwu_EventPackage_MarryTaiYuan.dll</HintPath>
    </Reference>
    <Reference Include="Taiwu_EventPackage_MarryXiangYang">
      <HintPath>$(TaiwuPath)\Event\EventLib\Taiwu_EventPackage_MarryXiangYang.dll</HintPath>
    </Reference>
    <Reference Include="Taiwu_EventPackage_MarryYangZhou">
      <HintPath>$(TaiwuPath)\Event\EventLib\Taiwu_EventPackage_MarryYangZhou.dll</HintPath>
    </Reference>
    <Reference Include="Taiwu_EventPackage_RoleTaiwuSelfMonthAdvanceEvents">
      <HintPath>$(TaiwuPath)\Event\EventLib\Taiwu_EventPackage_RoleTaiwuSelfMonthAdvanceEvents.dll</HintPath>
    </Reference>
    <Reference Include="Taiwu_EventPackage_SameBlockNpcMonthAdvanceEvents">
      <HintPath>$(TaiwuPath)\Event\EventLib\Taiwu_EventPackage_SameBlockNpcMonthAdvanceEvents.dll</HintPath>
    </Reference>
  </ItemGroup>


</Project>
